services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: eventlens
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Avant-garde100
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  api:
    build: ./api
    command: node server.js
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./db:/app/db
    depends_on:
      - postgres
      - redis

  ui:
    build: ./ui
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pgdata: